---
main: com.palace.web.DreamMainApp
---
server:
  port: 8099
spring:
  application:
    name: DreamMainApp
  profiles:
    active: "@profileActive@"
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    db0:
      maxPoolPreparedStatementPerConnectionSize: 20
      minIdle: 1
      maxOpenPreparedStatements: 50
      maxActive: 100
      testWhileIdle: true
      timeBetweenEvictionRunsMillis: 60000
      validationQuery: select 'x'
      filters: stat,log4j,config
      maxWait: 60000
      url: "@mysql0.url@"
      username: "@mysql0.username@"
      password: "@mysql0.password@"
      testOnBorrow: true
      poolPreparedStatements: true
      InitialSize: 1
      minEvictableIdleTimeMillis: 300000
      driverClassName: com.mysql.cj.jdbc.Driver
      testOnReturn: false
logging:
  config: classpath:logback-spring.xml

    

  
 