---
main: dream-web
---
server:
  port: 8009
spring:
  application:
    name: dream-web
  datasource:
    name: dream-web
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-pool-prepared-statement-per-connection-size: 20
      min-idle: 1
      max-open-prepared-statements: 50
      max-active: 100
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      validation-query: select 'x'
      filters: stat,log4j,config
      max-wait: 60000
      url: jdbc:mysql://68.168.137.110:3306/dream?useUnicode=true&autoReconnect=true&characterEncoding=UTF-8&socketTimeout=30000&connectTimeout=3000&allowMultiQueries=true
      username: root
      password: mysqldata8290080
      test-on-borrow: false
      pool-prepared-statements: true
      initial-size: 1
      min-evictable-idle-time-millis: 300000
      driver-class-name: com.mysql.cj.jdbc.Driver
      test-on-return: false
